# Site Settings
title: "OJ's Homepage"
description: "Bookmark this to keep an eye on my project updates!"
theme: jekyll-theme-Cayman

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge

# GitHub Pages Settings
baseurl: ""  # Empty for user pages (OJ-30.github.io)
url: "https://OJ-30.github.io"  # Your website URL

# Exclusions (Avoid unnecessary files in the build)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
